
services:
  web:
    image: tomee:jre25-Semeru-ubuntu-plus
    ports:
      - "8088:8080"
    networks:
      - app-network
    volumes:
      - ./target/viajesAPI-1.0-SNAPSHOT.war:/usr/local/tomee/webapps/travelTogether.war
    environment:
      - MYSQL_HOST=dbWeb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=traveltogether
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - dbWeb


  dbWeb:
    image: mysql:latest
    container_name: dbweb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: traveltogether
      MYSQL_PASSWORD: admin
    ports:
      - "3309:3306"
    networks:
      - app-network
    volumes:
      - dbWeb:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  web:
  dbWeb:

networks:
  app-network:
    driver: bridge